import { useEffect, useState, type ReactNode } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { ArrowDownRight, ArrowRight, ArrowUpRight, ChevronDown, Clock3, Instagram, MapPin, Menu, MessageCircle, MoveUpRight, Sparkles, X } from 'lucide-react';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Route, Router as WouterRouter, Switch, useLocation } from 'wouter';
import heroStore from '@assets/09_1789699587925.jpeg';
import facadeClose from '@assets/10_1789699587925.jpeg';
import counter from '@assets/01_1789699587921.jpeg';
import racksColor from '@assets/02_1789699587921.jpeg';
import denimWall from '@assets/03_1789699587922.jpeg';
import denimDetail from '@assets/04_1789699587922.jpeg';
import dresses from '@assets/05_1789699587923.jpeg';
import fittingRoom from '@assets/06_1789699587923.jpeg';
import displayWall from '@assets/07_1789699587923.jpeg';
import storeWide from '@assets/08_1789699587924.jpeg';

const queryClient = new QueryClient();
const whatsappHref = 'https://wa.me/5500000000000?text=Olá%20LOOK%2C%20quero%20montar%20um%20look';
const mapsHref = 'https://www.google.com/maps/search/?api=1&query=LOOK+Moda+Feminina';
const reveal = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: .72, ease: 'easeOut' as const } } };

function FadeIn({ children, delay = 0, className = '' }: { children: ReactNode; delay?: number; className?: string }) {
  return <motion.div className={className} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .16 }} variants={{ hidden: reveal.hidden, visible: { ...reveal.visible, transition: { ...reveal.visible.transition, delay } } }}>{children}</motion.div>;
}
function ButtonLink({ href, children, dark = false, className = '' }: { href: string; children: ReactNode; dark?: boolean; className?: string }) {
  return <a href={href} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noreferrer' : undefined} className={`group inline-flex items-center justify-center gap-3 rounded-full px-6 py-3.5 text-[.72rem] font-bold uppercase tracking-[.14em] transition-all duration-300 hover:-translate-y-0.5 ${dark ? 'bg-[#172236] text-[#f3ead8] hover:bg-[#ef6a6f]' : 'bg-[#ef6a6f] text-[#fff7eb] hover:bg-[#172236]'} ${className}`} data-testid="link-cta">{children}<ArrowRight size={16} className="transition-transform duration-300 group-hover:translate-x-1" /></a>;
}

function Header() {
  const [open, setOpen] = useState(false);
  const items = [['A LOOK', '#sobre'], ['A curadoria', '#curadoria'], ['Como funciona', '#como-funciona'], ['Visite', '#visite']];
  return <header className="absolute left-0 right-0 top-0 z-30 px-5 py-5 text-[#f7efdf] md:px-10 md:py-7"><div className="mx-auto flex max-w-[1360px] items-center justify-between"><a href="#inicio" className="group flex items-center gap-3" data-testid="link-logo"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-[#f7efdf]/45 text-sm font-bold transition-transform group-hover:rotate-12">L</span><span className="text-[1.1rem] font-bold tracking-[.3em]">LOOK</span></a><nav className="hidden items-center gap-8 md:flex">{items.map(([label, href]) => <a key={href} href={href} className="menu-link text-[.68rem] font-bold uppercase tracking-[.16em] text-[#f7efdf]/85" data-testid={`link-nav-${href.slice(1)}`}>{label}</a>)}</nav><a href={whatsappHref} target="_blank" rel="noreferrer" className="hidden items-center gap-2 rounded-full border border-[#f7efdf]/45 px-4 py-2.5 text-[.65rem] font-bold uppercase tracking-[.14em] transition-colors hover:bg-[#f7efdf] hover:text-[#172236] sm:flex" data-testid="link-header-whatsapp"><MessageCircle size={14} /> Falar com a LOOK</a><button onClick={() => setOpen(!open)} className="rounded-full border border-[#f7efdf]/45 p-2.5 md:hidden" aria-label="Abrir menu" data-testid="button-menu">{open ? <X size={19} /> : <Menu size={19} />}</button></div>{open && <div className="mx-auto mt-4 max-w-[1360px] rounded-2xl bg-[#f3ead8] p-5 text-[#172236] shadow-xl md:hidden"><div className="grid gap-4">{items.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)} className="border-b border-[#172236]/15 pb-3 text-sm font-bold uppercase tracking-[.12em]" data-testid={`link-mobile-${href.slice(1)}`}>{label}</a>)}</div></div>}</header>;
}

function Hero() {
  return <section id="inicio" className="relative min-h-[760px] overflow-hidden bg-[#172236] text-[#f7efdf] md:min-h-[850px]"><div className="absolute inset-0"><img src={heroStore} alt="Fachada da loja LOOK" className="hero-photo h-full w-full object-cover opacity-50" data-testid="img-hero-store" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(23,34,54,.96)_0%,rgba(23,34,54,.78)_39%,rgba(23,34,54,.18)_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(23,34,54,.82)_0%,transparent_40%)]" /></div><Header /><div className="relative mx-auto flex min-h-[760px] max-w-[1360px] items-end px-5 pb-16 pt-36 md:min-h-[850px] md:items-center md:px-10 md:pb-20"><div className="max-w-[820px]"><motion.p initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .2, duration: .7 }} className="eyebrow mb-6">Desde 2018 · moda feminina com escuta</motion.p><motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .35, duration: .85, ease: [.22,1,.36,1] }} className="hero-title serif max-w-[780px] text-[clamp(4.3rem,9vw,8.8rem)] leading-[.88] tracking-[-.065em]">Seu estilo,<br /><em className="text-[#ef6a6f]">do dia a dia</em><br />à festa.</motion.h1><motion.div initial={{ y: 24 }} animate={{ y: 0 }} transition={{ delay: .3, duration: .7 }} className="mt-8 flex max-w-[490px] flex-col gap-6 sm:flex-row sm:items-end"><p className="text-[.97rem] leading-[1.7] text-[#f7efdf]/78">Peças pensadas pro seu dia a dia e pros seus momentos especiais, com atendimento que te ajuda a montar o look certo — sem pressa e sem achismo.</p><ButtonLink href={whatsappHref}>Falar no WhatsApp</ButtonLink></motion.div><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.15 }} className="mt-3 text-[.66rem] uppercase tracking-[.12em] text-[#f7efdf]/55">Resposta rápida · sem compromisso</motion.p></div><div className="absolute bottom-8 right-8 hidden items-center gap-3 md:flex"><span className="text-[.62rem] uppercase tracking-[.2em] text-[#f7efdf]/70">Desça para conhecer</span><ArrowDownRight size={19} className="text-[#ef6a6f]" /></div></div></section>;
}
function Marquee() { return <div className="overflow-hidden bg-[#ef6a6f] py-3 text-[#fff7eb]"><div className="marquee-track flex items-center gap-7 text-[.67rem] font-bold uppercase tracking-[.2em]">{Array.from({ length: 2 }).flatMap((_, i) => ['curadoria própria', 'atendimento que escuta', 'do dia a dia à festa', '6 anos de LOOK'].map((text, j) => <span key={`${i}-${j}`} className="flex items-center gap-7">{text}<Sparkles size={13} /></span>))}</div></div>; }
function Intro() { return <section id="sobre" className="bg-[#f3ead8] px-5 py-24 md:px-10 md:py-36"><div className="mx-auto grid max-w-[1200px] gap-14 md:grid-cols-[.8fr_1.2fr] md:items-end"><FadeIn><div><p className="eyebrow mb-5">A ideia por trás da LOOK</p><p className="serif text-[clamp(2.7rem,5vw,5rem)] leading-[.97] tracking-[-.045em] text-[#172236]">Tem roupa que serve.<br /><em className="text-[#ef6a6f]">E tem roupa que combina com você.</em></p></div></FadeIn><FadeIn delay={.14}><div className="max-w-[540px] md:ml-auto"><p className="text-xl leading-[1.5] text-[#172236]">A LOOK existe pra isso: peças pro dia a dia e pra festa, escolhidas com curadoria própria — não é o mix genérico que você acha em qualquer loja.</p><p className="mt-6 leading-[1.7] text-[#172236]/65">Há mais de 6 anos ajudando mulheres a se vestirem do jeito delas, com atendimento que escuta antes de indicar.</p><a href="#curadoria" className="mt-8 inline-flex items-center gap-3 border-b border-[#172236] pb-2 text-[.7rem] font-bold uppercase tracking-[.14em]" data-testid="link-discover-collection">Vem conhecer a coleção <ArrowDownRight size={15} /></a></div></FadeIn></div></section>; }

function Gallery() {
  return <section id="curadoria" className="bg-[#e7ded0] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1360px]"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><FadeIn><div><p className="eyebrow mb-4">Um mix com ponto de vista</p><h2 className="serif max-w-[620px] text-[clamp(3rem,6vw,6.5rem)] leading-[.9] tracking-[-.055em]">Escolhido para<br /><em>fazer sentido.</em></h2></div></FadeIn><FadeIn delay={.12}><p className="max-w-[310px] text-sm leading-[1.7] text-[#172236]/65">Cor, textura, caimento e aquela peça que muda tudo. A loja é o nosso jeito de editar o guarda-roupa com você.</p></FadeIn></div><div className="grid grid-cols-2 gap-3 md:grid-cols-12 md:gap-5"><FadeIn className="col-span-2 md:col-span-5"><div className="photo-wrap relative h-[390px] md:h-[640px]"><img src={racksColor} alt="Araras coloridas da LOOK" className="h-full w-full object-cover" data-testid="img-gallery-racks" /><span className="absolute bottom-4 left-4 rounded-full bg-[#f3ead8] px-3 py-2 text-[.62rem] font-bold uppercase tracking-[.14em]">cores para viver</span></div></FadeIn><div className="col-span-2 grid grid-cols-2 gap-3 md:col-span-7 md:grid-cols-7 md:gap-5"><FadeIn delay={.08} className="col-span-1 md:col-span-4"><div className="photo-wrap h-[245px] md:h-[380px]"><img src={dresses} alt="Arara de vestidos para ocasiões especiais" className="h-full w-full object-cover" data-testid="img-gallery-dresses" /></div></FadeIn><FadeIn delay={.14} className="col-span-1 md:col-span-3"><div className="photo-wrap h-[245px] md:h-[380px]"><img src={displayWall} alt="Parede texturizada com vitrine de acessórios" className="h-full w-full object-cover" data-testid="img-gallery-display" /></div></FadeIn><FadeIn delay={.2} className="col-span-2 md:col-span-7"><div className="photo-wrap relative h-[280px] md:h-[240px]"><img src={denimWall} alt="Prateleiras com jeans e malhas" className="h-full w-full object-cover" data-testid="img-gallery-denim" /><div className="absolute inset-x-5 bottom-5 flex items-end justify-between text-[#f7efdf]"><span className="serif text-3xl italic">textura, sempre</span><ArrowUpRight size={22} /></div></div></FadeIn></div></div><div className="mt-5 grid gap-3 md:grid-cols-12 md:gap-5"><FadeIn className="md:col-span-4"><div className="photo-wrap h-[260px]"><img src={counter} alt="Balcão central da loja LOOK" className="h-full w-full object-cover" data-testid="img-gallery-counter" /></div></FadeIn><FadeIn delay={.1} className="md:col-span-8"><div className="photo-wrap h-[260px]"><img src={denimDetail} alt="Detalhe das prateleiras de jeans da LOOK" className="h-full w-full object-cover" data-testid="img-gallery-denim-detail" /></div></FadeIn></div></div></section>;
}

function Benefits() {
  const benefits = [['01', 'Atendimento personalizado', 'Você sai sabendo por que aquela peça é sua cara, não só “ficou bonito”.'], ['02', 'Do dia a dia à festa', 'Resolve o guarda-roupa inteiro em uma loja só, no seu ritmo.'], ['03', 'Curadoria com estilo próprio', 'Você não usa a roupa que “todo mundo” tem.'], ['04', 'Experiência de 6 anos', 'Uma equipe que já viu de tudo e sabe o que funciona em cada corpo.']];
  return <section className="bg-[#172236] px-5 py-24 text-[#f7efdf] md:px-10 md:py-36"><div className="mx-auto max-w-[1200px]"><div className="grid gap-14 md:grid-cols-[.7fr_1.3fr]"><FadeIn><div className="sticky top-10 self-start"><p className="eyebrow mb-5">Por que a LOOK</p><h2 className="serif text-[clamp(3rem,5vw,5.6rem)] leading-[.92] tracking-[-.05em]">Vista o que<br /><em className="text-[#ef6a6f]">é seu.</em></h2><p className="mt-7 max-w-[290px] text-sm leading-[1.7] text-[#f7efdf]/60">Atendimento personalizado → você não precisa descobrir tudo sozinha.</p></div></FadeIn><div>{benefits.map(([n, title, text], i) => <FadeIn key={n} delay={i * .08}><div className="reveal-card grid gap-4 border-t border-[#f7efdf]/20 py-7 md:grid-cols-[65px_1fr_1fr] md:items-start"><span className="text-[.68rem] font-bold tracking-[.18em] text-[#ef6a6f]">{n}</span><h3 className="serif text-3xl leading-none">{title}</h3><p className="max-w-[270px] text-sm leading-[1.65] text-[#f7efdf]/60">{text}</p></div></FadeIn>)}</div></div></div></section>;
}

function Process() {
  const steps = [['01', 'Você conta a ocasião', 'Dia a dia, trabalho, festa. A conversa começa pelo que você realmente precisa.'], ['02', 'A gente separa possibilidades', 'A equipe entende seu estilo e já deixa opções com sentido esperando por você.'], ['03', 'Você prova e decide', 'Na loja, pelo WhatsApp ou do seu jeito. Sem pressão, sem pressa.']];
  return <section id="como-funciona" className="bg-[#f3ead8] px-5 py-24 md:px-10 md:py-36"><div className="mx-auto max-w-[1200px]"><div className="grid gap-10 md:grid-cols-[.9fr_1.1fr]"><FadeIn><div><p className="eyebrow mb-5">Como funciona</p><h2 className="serif text-[clamp(3rem,6vw,6rem)] leading-[.9] tracking-[-.055em]">Comprar roupa<br /><em className="text-[#ef6a6f]">pode ser leve.</em></h2><p className="mt-8 max-w-[350px] text-sm leading-[1.7] text-[#172236]/65">Na LOOK, o atendimento é o ponto de partida, não um detalhe.</p></div></FadeIn><div>{steps.map(([n, title, text], i) => <FadeIn key={n} delay={i * .12}><div className="flex gap-5 border-t border-[#172236]/20 py-7"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#ef6a6f] text-[.65rem] font-bold text-[#fff7eb]">{n}</span><div><h3 className="serif text-3xl">{title}</h3><p className="mt-2 max-w-[390px] text-sm leading-[1.7] text-[#172236]/62">{text}</p></div></div></FadeIn>)}</div></div><FadeIn delay={.18}><div className="mt-16 grid gap-4 md:grid-cols-12"><div className="photo-wrap h-[380px] md:col-span-7 md:h-[490px]"><img src={storeWide} alt="Vista ampla do interior da loja LOOK" className="h-full w-full object-cover" data-testid="img-process-store" /></div><div className="photo-wrap h-[380px] md:col-span-5 md:h-[490px]"><img src={fittingRoom} alt="Provador da loja LOOK" className="h-full w-full object-cover" data-testid="img-process-fitting" /></div></div></FadeIn></div></section>;
}

function Visit() {
  return <section id="visite" className="bg-[#ef6a6f] px-5 py-24 text-[#fff7eb] md:px-10 md:py-32"><div className="mx-auto grid max-w-[1200px] gap-12 md:grid-cols-[1.1fr_.9fr] md:items-center"><FadeIn><div><p className="eyebrow !text-[#172236]">Quando estiver pronta</p><h2 className="serif mt-5 max-w-[680px] text-[clamp(3.3rem,7vw,7.2rem)] leading-[.88] tracking-[-.06em]">Seu estilo não precisa ser igual ao de mais ninguém.</h2><p className="mt-8 max-w-[470px] text-lg leading-[1.55] text-[#fff7eb]/85">Vem na LOOK e deixa a gente te ajudar a montar o look certo — pro hoje e pra qualquer ocasião que vier.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href={whatsappHref} dark>Falar no WhatsApp agora</ButtonLink><a href={mapsHref} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-[#fff7eb]/60 px-6 py-3.5 text-[.7rem] font-bold uppercase tracking-[.14em] transition hover:bg-[#fff7eb] hover:text-[#172236]" data-testid="link-maps"><MapPin size={16} /> Ver no mapa</a></div></div></FadeIn><FadeIn delay={.15}><div className="photo-wrap relative h-[450px] rotate-2 md:h-[600px]"><img src={facadeClose} alt="Detalhe da fachada da LOOK" className="h-full w-full object-cover" data-testid="img-visit-facade" /><div className="absolute -bottom-5 -left-4 rounded-full bg-[#f3ead8] px-5 py-3 text-[.68rem] font-bold uppercase tracking-[.13em] text-[#172236]">Rua … · nº 154</div></div></FadeIn></div></section>;
}

function FAQ() {
  const faqs = [['Dá pra ver as peças pelo WhatsApp antes de ir?', 'Sim, é só chamar e a equipe te manda opções.'], ['Tem roupa pra ocasião de festa e formatura?', 'Sim, a curadoria cobre do dia a dia até eventos especiais.'], ['Vocês têm peças de outros tamanhos?', 'Informação de numeração disponível com a equipe — confirme pelo WhatsApp.'], ['Qual o horário de funcionamento?', 'Horários reais ainda precisam ser inseridos antes da publicação.'], ['Tem parcelamento no cartão?', 'Condição real de pagamento ainda precisa ser inserida antes da publicação.']];
  const [open, setOpen] = useState<number | null>(0);
  return <section className="bg-[#e7ded0] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1000px]"><div className="mb-12 text-center"><p className="eyebrow mb-4">Antes de vir</p><h2 className="serif text-[clamp(3rem,6vw,5.6rem)] leading-[.9] tracking-[-.05em]">Pode perguntar.</h2></div><div className="border-t border-[#172236]/25">{faqs.map(([question, answer], i) => <div key={question} className="border-b border-[#172236]/25"><button onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between gap-5 py-6 text-left" data-testid={`button-faq-${i}`}><span className="serif text-xl md:text-2xl">{question}</span><ChevronDown size={19} className={`shrink-0 transition-transform ${open === i ? 'rotate-180 text-[#ef6a6f]' : ''}`} /></button><div className={`faq-content ${open === i ? 'open' : 'closed'}`}><p className="max-w-[650px] pb-6 text-sm leading-[1.7] text-[#172236]/65">{answer}</p></div></div>)}</div><p className="mx-auto mt-8 max-w-[660px] text-center text-[.68rem] uppercase leading-[1.6] tracking-[.08em] text-[#172236]/48">Nota de publicação: avaliações, endereço completo, horários, formas de pagamento e política de troca reais precisam ser adicionados antes de publicar.</p></div></section>;
}

function Footer() {
  return <footer className="bg-[#172236] px-5 py-12 text-[#f7efdf] md:px-10"><div className="mx-auto max-w-[1360px]"><div className="grid gap-10 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-[#f7efdf]/40 text-sm font-bold">L</span><span className="text-[1.1rem] font-bold tracking-[.3em]">LOOK</span></div><p className="mt-5 max-w-[260px] text-sm leading-[1.7] text-[#f7efdf]/55">6 anos vestindo mulheres com estilo próprio.</p></div><div><p className="eyebrow mb-4">Visite</p><p className="text-sm leading-[1.8] text-[#f7efdf]/65">Endereço completo<br />[inserir cidade e estado]<br />nº 154</p><a href={mapsHref} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] text-[#ef6a6f]" data-testid="link-footer-map">Abrir no mapa <MoveUpRight size={13} /></a></div><div><p className="eyebrow mb-4">Conversa</p><a href={whatsappHref} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-sm text-[#f7efdf]/75 hover:text-[#ef6a6f]" data-testid="link-footer-whatsapp"><MessageCircle size={15} /> WhatsApp placeholder</a><a href="#" className="mt-4 flex items-center gap-2 text-sm text-[#f7efdf]/75 hover:text-[#ef6a6f]" data-testid="link-footer-instagram"><Instagram size={15} /> Instagram da LOOK</a></div><div><p className="eyebrow mb-4">Horários</p><p className="flex items-start gap-2 text-sm leading-[1.7] text-[#f7efdf]/55"><Clock3 size={15} className="mt-1 shrink-0" /> [inserir horários reais]</p></div></div><div className="mt-14 flex flex-col justify-between gap-3 border-t border-[#f7efdf]/15 pt-5 text-[.62rem] uppercase tracking-[.12em] text-[#f7efdf]/35 md:flex-row"><span>© LOOK Moda Feminina · São Paulo, Brasil</span><span>Feito para vestir você, não a tendência.</span></div></div></footer>;
}

function Home() {
  useEffect(() => {
    document.title = 'LOOK — Seu estilo, do dia a dia à festa';
    const description = 'Moda feminina com curadoria própria e atendimento personalizado. Há mais de 6 anos vestindo mulheres com estilo próprio.';
    let meta = document.querySelector('meta[name="description"]');
    if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name', 'description'); document.head.appendChild(meta); }
    meta.setAttribute('content', description);
  }, []);
  return <main className="look-page grain"><Hero /><Marquee /><Intro /><Gallery /><Benefits /><Process /><Visit /><FAQ /><Footer /></main>;
}
function Router() { return <RoutedErrorBoundary><Switch><Route path="/" component={Home} /><Route component={NotFound} /></Switch></RoutedErrorBoundary>; }
function RoutedErrorBoundary({ children }: { children: ReactNode }) { const [location] = useLocation(); return <ErrorBoundary resetKey={location}>{children}</ErrorBoundary>; }
function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>; }
export default App;